export const Place = state => state.place
export const RouteList = state => state.routeList
export const RouteIsShow = state => state.routeIsShow
export const TransferList = state => state.transferList
export const TransferIsShow = state => state.transferIsShow
export const SynsStationList = state => state.synsStationList
export const SynsStationShow = state => state.synsStationShow
export const StationList = state => state.stationList
export const StationShow = state => state.stationShow
export const RealTimeBus = state => state.realTimeBus
export const StaName = state => state.staName